# Oral History as Data (OHD) - a Lib-STATIC Tool
# https://github.com/uidaholib/oral-history-as-data


##########
# URL settings 
#
# url is your gh-pages base, following the pattern: username.github.io
url: https://clamb89.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: strickland
# repository is the github repository's full url
repository: https://github.com/clamb89/strickland


##########
# Site settings
#
# title of site appears in banner
title: Lamb's Example Site
# tagline appears in banner
tagline: Let's hope this works!
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: CDIL preliminary training


####### Leave the Below As Is ########

# Jekyll collections settings
collections:
  transcripts:
    output: true
    permalink: /:collection/:name
  howto:
    output: true
    permalink: /:collection/:name
# defaults
defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: howto
    values:
      layout: howto

# Build settings
markdown: kramdown

